/** Curated US liquid names — paginated 10-at-a-time via /api/quotes */
export const WATCHLIST: { symbol: string; company: string }[] = [
  { symbol: "AAPL", company: "Apple" },
  { symbol: "MSFT", company: "Microsoft" },
  { symbol: "GOOGL", company: "Alphabet" },
  { symbol: "AMZN", company: "Amazon" },
  { symbol: "NVDA", company: "NVIDIA" },
  { symbol: "META", company: "Meta" },
  { symbol: "TSLA", company: "Tesla" },
  { symbol: "JPM", company: "JPMorgan" },
  { symbol: "V", company: "Visa" },
  { symbol: "MA", company: "Mastercard" },
  { symbol: "JNJ", company: "Johnson & Johnson" },
  { symbol: "WMT", company: "Walmart" },
  { symbol: "PG", company: "Procter & Gamble" },
  { symbol: "XOM", company: "Exxon Mobil" },
  { symbol: "CVX", company: "Chevron" },
  { symbol: "HD", company: "Home Depot" },
  { symbol: "BAC", company: "Bank of America" },
  { symbol: "KO", company: "Coca-Cola" },
  { symbol: "PEP", company: "PepsiCo" },
  { symbol: "COST", company: "Costco" },
  { symbol: "AVGO", company: "Broadcom" },
  { symbol: "CRM", company: "Salesforce" },
  { symbol: "NFLX", company: "Netflix" },
  { symbol: "AMD", company: "AMD" },
  { symbol: "INTC", company: "Intel" },
  { symbol: "ORCL", company: "Oracle" },
  { symbol: "CSCO", company: "Cisco" },
  { symbol: "DIS", company: "Disney" },
  { symbol: "NKE", company: "Nike" },
  { symbol: "MCD", company: "McDonald's" },
  { symbol: "ADBE", company: "Adobe" },
  { symbol: "IBM", company: "IBM" },
  { symbol: "QCOM", company: "Qualcomm" },
  { symbol: "TXN", company: "Texas Instruments" },
  { symbol: "UBER", company: "Uber" },
  { symbol: "ABNB", company: "Airbnb" },
  { symbol: "PYPL", company: "PayPal" },
  { symbol: "SQ", company: "Block" },
  { symbol: "SHOP", company: "Shopify" },
  { symbol: "SPOT", company: "Spotify" },
];

export const PAGE_SIZE = 10;
